const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
    entry:path.join(__dirname,'src','main.js'),
    output:{
        filename:'bundle.js',
        path:path.join(__dirname,'dist')
    },
    mode:'development',
    plugins:[
        new HtmlWebpackPlugin ({
            template:'./src/index.html'
        })
    ],
    module:{
        rules:[
            {
                test:/\.css$/,
                use:['style-loader','css-loader']
            },
            {
                test:/\.less$/,
                use:['style-loader','css-loader','less-loader']
            },
            {
                test:/\.(png|jpg|gif)$/,
                use:{
                    loader:'url-loader',
                    options:{
                        limit:30*1024
                    }
                }
            },
            {
                test:/\.(woff|ttf|eot|svg)$/,
                use:{
                    loader:'url-loader',
                    options:{
                        limit:30*1024
                    }
                }
            },
            {
                test:/\.js$/,
                exclude:/node_modules/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['@babel/preset-env']
                    }
                }
            }
        ]
    },
    devServer:{
        open:true,
        hot:true
    }
}